package com.know.service;
import com.know.domain.*;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
 @Service public class TimerService {private final TimeEntryRepository entries;private final PathRepository paths;private final ItemRepository items;private final PathItemRepository pathItems;private final ProgressEntryRepository progress;private final ActivityRepository activities;public TimerService(TimeEntryRepository entries,PathRepository paths,ItemRepository items,PathItemRepository pathItems,ProgressEntryRepository progress,ActivityRepository activities){this.entries=entries;this.paths=paths;this.items=items;this.pathItems=pathItems;this.progress=progress;this.activities=activities;}
 public record TimeView(UUID id,UUID pathId,UUID itemId,Instant startedAt,Instant endedAt,Long durationSeconds,String description,TimeSource source,boolean running){static TimeView of(TimeEntry e){return new TimeView(e.getId(),e.getPathId(),e.getItemId(),e.getStartedAt(),e.getEndedAt(),e.getDurationSeconds(),e.getDescription(),e.getSource(),e.running());}}
 @Transactional public TimeView start(UUID userId,UUID pathId,UUID itemId,String description,TimeSource source){if(entries.findByUserIdAndEndedAtIsNull(userId).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"A timer is already running");validateTargets(userId,pathId,itemId);TimeEntry e;try{e=entries.save(new TimeEntry(userId,pathId,itemId,Instant.now(),description,source==null?TimeSource.WEB:source));}catch(DataIntegrityViolationException ex){throw new ResponseStatusException(HttpStatus.CONFLICT,"A timer is already running");}activities.save(new Activity(userId,pathId,itemId,ActivityType.TIMER_STARTED,"Started a timer",description));return TimeView.of(e);}
 @Transactional public TimeView stop(UUID userId,UUID id){TimeEntry e=entries.findById(id).filter(x->x.getUserId().equals(userId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Timer not found"));if(!e.running())return TimeView.of(e);e.stop(Instant.now());entries.save(e);activities.save(new Activity(userId,e.getPathId(),e.getItemId(),ActivityType.TIMER_STOPPED,"Tracked "+e.getDurationSeconds()+" seconds",e.getDescription()));return TimeView.of(e);}
 @Transactional public void cancel(UUID userId,UUID id){TimeEntry e=entries.findById(id).filter(x->x.getUserId().equals(userId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Timer not found"));if(!e.running())throw new ResponseStatusException(HttpStatus.CONFLICT,"Only running timers can be cancelled");entries.delete(e);}
 @Transactional public TimeView configureRunning(UUID userId,UUID id,UUID pathId,UUID itemId,Instant startedAt,String description){if(startedAt==null||startedAt.isAfter(Instant.now()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Timer start cannot be in the future");validateTargets(userId,pathId,itemId);TimeEntry e=entries.findByIdAndUserId(id,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Timer not found"));if(!e.running())throw new ResponseStatusException(HttpStatus.CONFLICT,"Only a running timer can be configured");e.reconfigureRunning(pathId,itemId,startedAt,description);return TimeView.of(entries.save(e));}
 public TimeView current(UUID userId){return entries.findByUserIdAndEndedAtIsNull(userId).map(TimeView::of).orElse(null);}
 public List<TimeView> history(UUID userId){return entries.findAllByUserIdOrderByStartedAtDesc(userId,org.springframework.data.domain.PageRequest.of(0,100)).stream().map(TimeView::of).toList();}
 @Transactional public TimeView manual(UUID userId,UUID pathId,UUID itemId,Instant startedAt,Instant endedAt,String description){if(startedAt==null||endedAt==null||endedAt.isBefore(startedAt))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid time range");validateTargets(userId,pathId,itemId);TimeEntry e=new TimeEntry(userId,pathId,itemId,startedAt,description,TimeSource.MANUAL);e.stop(endedAt);entries.save(e);activities.save(new Activity(userId,pathId,itemId,ActivityType.TIME_TRACKED,"Tracked "+e.getDurationSeconds()+" seconds",description));return TimeView.of(e);}
 @Transactional public TimeView edit(UUID userId,UUID id,UUID pathId,UUID itemId,Instant startedAt,Instant endedAt,String description){if(startedAt==null||endedAt==null||endedAt.isBefore(startedAt))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invalid time range");validateTargets(userId,pathId,itemId);TimeEntry e=entries.findByIdAndUserId(id,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Time entry not found"));if(e.running())throw new ResponseStatusException(HttpStatus.CONFLICT,"Running timers must be stopped before editing");e.edit(pathId,itemId,startedAt,endedAt,description);entries.save(e);return TimeView.of(e);}
 public Statistics statistics(UUID userId){Instant now=Instant.now();java.time.LocalDate date=java.time.LocalDate.now(java.time.ZoneOffset.UTC);Instant dayStart=date.atStartOfDay(java.time.ZoneOffset.UTC).toInstant();Instant weekStart=date.minusDays(6).atStartOfDay(java.time.ZoneOffset.UTC).toInstant();Instant monthStart=date.withDayOfMonth(1).atStartOfDay(java.time.ZoneOffset.UTC).toInstant();Instant windowStart=monthStart.isBefore(weekStart)?monthStart:weekStart;List<TimeEntry> window=entries.findAllByUserIdAndStartedAtBetweenOrderByStartedAtDesc(userId,windowStart,now);List<TimeEntry> today=window.stream().filter(e->!e.getStartedAt().isBefore(dayStart)).toList();List<TimeEntry> week=window.stream().filter(e->!e.getStartedAt().isBefore(weekStart)).toList();List<TimeEntry> month=window.stream().filter(e->!e.getStartedAt().isBefore(monthStart)).toList();List<ProgressChange> changes=progress.findTop10ByUserIdOrderByChangedAtDesc(userId).stream().map(e->new ProgressChange(e.getItemId(),e.getPreviousProgress(),e.getNewProgress(),e.getChangedAt())).toList();return new Statistics(sum(today),sum(week),sum(month),group(today,TimeEntry::getPathId),group(today,TimeEntry::getItemId),items.countByUserIdAndStatus(userId,ItemStatus.COMPLETED),items.countByUserIdAndStatus(userId,ItemStatus.ACTIVE),changes);}
 private long liveSeconds(TimeEntry e){return e.getDurationSeconds()==null?Math.max(0,Duration.between(e.getStartedAt(),Instant.now()).toSeconds()):e.getDurationSeconds();}private long sum(List<TimeEntry> list){return list.stream().mapToLong(this::liveSeconds).sum();}private Map<UUID,Long> group(List<TimeEntry> list,java.util.function.Function<TimeEntry,UUID> key){Map<UUID,Long> out=new LinkedHashMap<>();for(TimeEntry e:list)if(key.apply(e)!=null)out.merge(key.apply(e),liveSeconds(e),Long::sum);return out;}public record ProgressChange(UUID itemId,short previousProgress,short newProgress,Instant changedAt){}public record Statistics(long todaySeconds,long weekSeconds,long monthSeconds,Map<UUID,Long> todayByPath,Map<UUID,Long> todayByItem,long completedItems,long activeItems,List<ProgressChange> recentProgressChanges){}
 private void validateTargets(UUID userId,UUID pathId,UUID itemId){if(pathId!=null){Path path=paths.findByIdAndUserId(pathId,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Path does not belong to user"));if(path.getStatus()!=PathStatus.ACTIVE)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Archived paths cannot receive new time");}if(itemId!=null)items.findByIdAndUserId(itemId,userId).orElseThrow(()->new ResponseStatusException(HttpStatus.BAD_REQUEST,"Item does not belong to user"));if(pathId!=null&&itemId!=null&&!pathItems.existsByIdPathIdAndIdItemId(pathId,itemId))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Item is not attached to the selected path");}
}
